import { StyleSheet } from 'react-native';

export const gameScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  header: {
    padding: 20,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  sessionInfo: {
    fontSize: 16,
    color: '#666',
    marginTop: 5,
  },
  subtitle: {
    fontSize: 18,
    marginTop: 10,
    color: '#007AFF',
    fontWeight: '600',
  },
  replacementInfo: {
    fontSize: 14,
    color: '#FF6B35',
    marginTop: 5,
    fontWeight: '500',
  },
  instruction: {
    fontSize: 14,
    color: '#666',
    marginTop: 5,
    textAlign: 'center',
  },
  addButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 15,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  selectionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 15,
  },
  validateButton: {
    backgroundColor: '#28A745',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
  },
  validateButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  regenerateButton: {
    backgroundColor: '#FFC107',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
  },
  regenerateButtonText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
    marginTop: 10,
  },
  photoGrid: {
    flex: 1,
  },
  grid: {
    padding: 10,
    justifyContent: 'center',
  },
  imageContainer: {
    position: 'relative',
    margin: 5,
  },
  imageDisabled: {
    opacity: 0.5,
  },
  image: {
    width: 150,
    height: 150,
    borderRadius: 10,
    backgroundColor: '#e0e0e0',
  },
  replacementBadge: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  replacementText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  addPhotoSlot: {
    width: 150,
    height: 150,
    margin: 5,
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
    borderWidth: 2,
    borderColor: '#007AFF',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addPhotoText: {
    fontSize: 40,
    color: '#007AFF',
    fontWeight: 'bold',
  },
  addPhotoSubtext: {
    fontSize: 14,
    color: '#007AFF',
    marginTop: 5,
  },
  selectionOverlay: {
    position: 'absolute',
    bottom: 5,
    left: 5,
    right: 5,
    backgroundColor: 'rgba(255, 193, 7, 0.9)',
    borderRadius: 5,
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  selectionText: {
    color: '#333',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  footer: {
    padding: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
});
